select * from customer1 limit 10

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer1 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer1
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer1)

--Q3 Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as avg_product_rating
from customer1
group by item_purchased
order by avg_product_rating desc
limit 5

---Q4. Compare the average Purchase Amounts between Standard and Express Shipping
select shipping_type,avg(purchase_amount) as avg_purchase_amt
from customer1
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
     --between subscribers and non-subscribers.
select subscription_status,count(customer_id),round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from customer1
group by subscription_status
order by avg_spend desc,total_revenue desc
limit 10

--Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer1
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer1)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rnk
from customer1
group by 1,2
)
select item_rnk,category,item_purchased,total_orders
from item_counts
where item_rnk<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer1
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer1
group by age_group
order by total_revenue desc
